apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-douban-anonymous
  labels:
    rbac.authorization.halo.run/aggregate-to-anonymous: "true"
    halo.run/role-template: "true"
    halo.run/hidden: "true"
  annotations:
    rbac.authorization.halo.run/display-name: "查看朋友圈提交模板"
rules:
  - apiGroups: [ "api.douban.moony.la" ]
    resources: [ "doubanmovies","doubanmovies/genres","doubanmovies/getDoubanDetail"]
    verbs: [ "get", "list" ]

---

apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-douban-view
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "豆瓣"
    rbac.authorization.halo.run/display-name: "豆瓣查看"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:douban:view"]
rules:
  - apiGroups: [ "douban.moony.la" ]
    resources: [ "doubanmovies"]
    verbs: [ "get", "list" ]

---

apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-douban-manage
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "豆瓣"
    rbac.authorization.halo.run/display-name: "豆瓣管理"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:douban:manage"]
    rbac.authorization.halo.run/dependencies: |
      ["role-template-douban-view"]
rules:
  - apiGroups: [ "douban.moony.la" ]
    resources: [ "doubanmovies"]
    verbs: [ "create", "patch", "update", "delete", "deletecollection" ]
  - nonResourceURLs: [ "/apis/api.plugin.halo.run/v1alpha1/plugins/plugin-douban/douban/*"]
    verbs: [ "create" , "delete" ]