apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-douban-settings
spec:
  forms:
    - group: base
      label: 基本设置
      formSchema:
        - $formkit: text
          label: 页面标题
          name: title
          validation: required
          value: '豆瓣记录'
        - $formkit: text
          label: 豆瓣的ID
          name: doubanId
          help: 我的豆瓣 https://www.douban.com/people/xxxx  xxxx 就是你的ID
        - $formkit: text
          label: TMDB API Key
          name: apiKey
          help: 设置TMDB API Key在https://www.themoviedb.org/settings/api 自行申请
        - $formkit: radio
          label: 启用代理
          name: isProxy
          id: isProxy
          value: false
          help: 如果用豆瓣源的图片很慢可以自己搭建给图片反代站点
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
        - $formkit: text
          if: "$get(isProxy).value === true"
          label: 代理地址
          name: proxyHost
          value: ""
          help: "搭建教程：https://docs.kunkunyu.com/docs/plugin-douban/use#%E9%85%8D%E7%BD%AE%E5%9B%BE%E7%89%87%E4%BB%A3%E7%90%86"